### ISSUE TITLE
download data

### ISSUE THREAD

**Issue by momonala** [gwwang16/MLND-Capstone-Project-DeepTesla#1]
can you provide the link where you downloaded the data? Thanks

**Comment by gwwang16** [comment]
@momonala , the original code is published on here [Github](https://github.com/lexfridman/deeptesla).
These data are collected by Lex's team using Tesla, more info can be found in lecture slides of this public [course](http://selfdrivingcars.mit.edu).

**Comment by momonala** [comment]
Thanks, I just realized that the data is in video form, and not as individual images. I was just looking in the wrong place, thanks.
